name: Build and run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build (with features)
      run: cargo build --all-features
    - name: Run doctests
      run: cargo test --package fs3000-rs --doc
    - name: Run unit tests
      run: cargo test --package fs3000-rs --lib
